-- OUR SPACE database + storage setup
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'My Love',
  role text not null check (role in ('boy','girl')),
  created_at timestamptz not null default now()
);

create table if not exists public.couples (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  boy_id uuid references public.profiles(id) on delete set null,
  girl_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text,
  image_url text,
  created_at timestamptz not null default now(),
  constraint notes_has_content check (
    coalesce(length(trim(text)), 0) > 0 or image_url is not null
  )
);

alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.notes enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "couples member select" on public.couples;
create policy "couples member select" on public.couples
for select using (auth.uid() = boy_id or auth.uid() = girl_id);

drop policy if exists "notes member select" on public.notes;
create policy "notes member select" on public.notes
for select using (
  exists (
    select 1 from public.couples c
    where c.id = notes.couple_id
      and (c.boy_id = auth.uid() or c.girl_id = auth.uid())
  )
);

drop policy if exists "notes member insert" on public.notes;
create policy "notes member insert" on public.notes
for insert with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.couples c
    where c.id = notes.couple_id
      and (c.boy_id = auth.uid() or c.girl_id = auth.uid())
  )
);

-- RPC: create a new couple and return {couple_id, code}
create or replace function public.create_couple(p_role text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  cid uuid;
  ccode text;
  uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if p_role not in ('boy','girl') then raise exception 'Invalid role'; end if;

  if exists(select 1 from public.couples where boy_id=uid or girl_id=uid) then
    raise exception 'You are already in a couple';
  end if;

  loop
    ccode := upper(substr(encode(gen_random_bytes(4),'hex'),1,6));
    exit when not exists(select 1 from public.couples where code=ccode);
  end loop;

  cid := gen_random_uuid();
  if p_role = 'boy' then
    insert into public.couples(id,code,boy_id) values(cid,ccode,uid);
  else
    insert into public.couples(id,code,girl_id) values(cid,ccode,uid);
  end if;

  return json_build_object('couple_id',cid,'code',ccode);
end;
$$;

-- RPC: join an existing couple by code
create or replace function public.join_couple(p_code text, p_role text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  cid uuid;
  uid uuid := auth.uid();
  r public.couples%rowtype;
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if p_role not in ('boy','girl') then raise exception 'Invalid role'; end if;
  if exists(select 1 from public.couples where boy_id=uid or girl_id=uid) then
    raise exception 'You are already in a couple';
  end if;

  select * into r from public.couples where code=upper(trim(p_code)) for update;
  if not found then raise exception 'Couple code not found'; end if;

  if p_role='boy' then
    if r.boy_id is not null then raise exception 'Boy side is already connected'; end if;
    update public.couples set boy_id=uid where id=r.id;
  else
    if r.girl_id is not null then raise exception 'Girl side is already connected'; end if;
    update public.couples set girl_id=uid where id=r.id;
  end if;

  return json_build_object('couple_id',r.id,'code',r.code);
end;
$$;

grant execute on function public.create_couple(text) to authenticated;
grant execute on function public.join_couple(text,text) to authenticated;

-- Storage bucket for MVP. It is public so widgets can display images by URL.
insert into storage.buckets (id,name,public)
values ('media','media',true)
on conflict (id) do update set public=true;

drop policy if exists "media authenticated upload" on storage.objects;
create policy "media authenticated upload" on storage.objects
for insert to authenticated
with check (bucket_id='media');

drop policy if exists "media authenticated delete" on storage.objects;
create policy "media authenticated delete" on storage.objects
for delete to authenticated
using (bucket_id='media');

-- The bucket is public for reads. For a production/private release,
-- switch to private storage and signed URLs.
